### ISSUE TITLE
Country flags doesn't expand when clicking more

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#269]
From a customer:

> I just realized the section showing the country flags doesn't expand when I click the 'more' button. It switches to 'less' but the list doesn't change. I couldn't be sure if this was intentional or a bug.

![image](https://user-images.githubusercontent.com/1079135/77115892-70669680-6a2f-11ea-87b5-a10b6b2f8e0f.png)

**Comment by Macro-Jackson** [comment]
Confirmed. Same here. Four countries. More... button does not do anything (except change to less).

**Comment by adriaanvanrossum** [comment]
Will deploy your PR. Can we close this after @hellodeibu?

**Comment by hellodeibu** [comment]
Hi @Macro-Jackson! The new update that has been pushed should both fix this bug and slightly enhance the behavior of the countries list. Could you let us know if it looks better for you now, too? Thanks so much!

**Comment by Macro-Jackson** [comment]
Uhhhmmm, now the more less button is completely gone and all countries are shown. 
Is that intended?

**Comment by hellodeibu** [comment]
Indeed it is yes :).

To elaborate; the list tries to show up to 10 countries, but there was a small bug with how the cut-off was handled when not enough countries matched the display criteria. This resulted in the more/less button being confused into thinking there was more to show, even though the remainder of the list didn’t actually meet the original display criteria. 

This button bug is now solved, and in addition to that if the list is short of making it to ten, the requirement of showing a country only if it had at least a 1% share is dropped, so the list can display more items once again.

**Comment by ege-erdogan** [comment]
So if I am getting this right, it is still not possible to see 10+ countries like we can see all entries in the referral section. That was the behavior I had in mind when I first submitted the ticket.

**Comment by adriaanvanrossum** [comment]
If there are more than 10 countries to show, it will show them, I think. If you check [our public dashboard](https://simpleanalytics.com/simpleanalytics.com) it shows the more button because there are more countries to show. Do you expect more countries to show there? As in, are there countries missing? If so, please let us know your domain, so we can check.

**Comment by hellodeibu** [comment]
What Adriaan said is correct, sorry I didn't describe it very well in my previous comment. The list tries to show up to 10 countries, and if there are more to be a shown a "more" button is displayed. Previously there were cases where there were not enough countries that matched the display criteria (have at least a 1% share), making the list rather short. In addition to that there was a bug with the more/less button in that situation too. This bug is fixed, and the criteria has been tweaked so that, if available, more countries are being shown in these cases too.
